---
title: "`r paste('Model', params$model_name)`"
author: "Thanasi Bakis, Anjali Krishnan"
params:
  model_name: 1
---

```{r child="includes/setup.Rmd"}
```


```{r child="includes/retrieve_data.Rmd"}
```


Reduce dimensionality of the music and news features

```{r}
if(file.exists(FEATURES_FILE)) {
  
  load(FEATURES_FILE)
  
} else {
  
  PCA_songs <- dataset %>%
  	select(songpositivity,   songnegativity, songneutrality, songsentiment,
  		   acousticness,     danceability,   duration_ms,    energy,
  		   instrumentalness, key,            liveness,       loudness,
  		   mode,             speechiness,    tempo,          time_signature,
  		   valence,          peakpos,        weeks,
  		   starts_with(c("songmin", "songmax"))) %>%
  	prcomp() %>%
  	magrittr::extract2("x") %>%
  	magrittr::extract(, 1:30) %>%
  	as.data.frame() %>%
  	setNames(paste0("song_", colnames(.)))
  
  
  PCA_news <- dataset %>%
  	select(newspositivity,   newsnegativity, newsneutrality, newssentiment,
  		   starts_with(c("newsmin", "newsmax"))) %>%
  	prcomp() %>%
  	magrittr::extract2("x") %>%
  	magrittr::extract(, 1:30) %>%
  	as.data.frame() %>%
  	setNames(paste0("news_", colnames(.)))
  
  save(PCA_songs, PCA_news, file = FEATURES_FILE)
  
}
```


Generate the model formula with all the interaction terms

```{r}
formula <- expand_grid(PC_song = colnames(PCA_songs), PC_news = colnames(PCA_news)) %>%
	mutate(interaction = paste(PC_song, PC_news, sep = ":")) %>%
	pull(interaction) %>%
	paste(collapse = " + ") %>%
	paste("response ~", . )
```


Merge the two PCA data frames with the response values to get one dataset

```{r}
features <- dataset %>%
	mutate(response = factor(rank < lastpos)) %>%
	select(response) %>%
	cbind(PCA_songs, PCA_news)
```


Train-test split

```{r message=FALSE, warning=FALSE}
training_data <- features %>%
	sample_frac(0.5)

testing_data <- anti_join(features, training_data)
```


Fit the model

```{r message=FALSE, warning=FALSE}
if(file.exists(MODEL_FILE)) {
  
  load(MODEL_FILE)
  
} else {
  
  model <- glm(formula, data = training_data, family = "binomial")
  summary(model)
  
  save(model, file = MODEL_FILE)
  
}
```


Make predictions and assess accuracy

```{r}
predictions <- testing_data %>%
  mutate(soft_prediction = predict(model, newdata = ., type = "response")) %>%
  mutate(hard_prediction = soft_prediction >= 0.5) %>%
  mutate(is_correct      = hard_prediction == response)

paste("Accuracy: ", 100*round(mean(predictions$is_correct), 4), "%", sep = '')
```


```{r child="includes/prediction_distributions.Rmd"}
```


```{r child="includes/soft_prediction_distribution.Rmd"}
```


```{r child="includes/roc.Rmd"}
```

