---
title: "`r paste('Model', params$model_name)`"
author: "Thanasi Bakis, Anjali Krishnan"
params:
  model_name: 2
---

```{r child="includes/setup.Rmd"}
```


```{r child="includes/retrieve_data.Rmd"}
```


Our interaction terms will be defined as principal components (linear combinations of the original features)

```{r}
if(file.exists(FEATURES_FILE)) {
  
  load(FEATURES_FILE)
  
} else {
  
  PCA <- dataset %>%
  	select(songpositivity,   songnegativity, songneutrality, songsentiment,
  		     acousticness,     danceability,   duration_ms,    energy,
  		     instrumentalness, key,            liveness,       loudness,
  		     mode,             speechiness,    tempo,          time_signature,
  		     valence,          peakpos,        weeks,          lastpos,
  		     starts_with(c("songmin", "songmax")),
  
  		     newspositivity,   newsnegativity, newsneutrality, newssentiment,
  		     starts_with(c("newsmin", "newsmax"))) %>%
  	prcomp()
  
  features <- PCA %>%
  	magrittr::extract2("x") %>%
  	as.data.frame() %>%
    mutate(response = factor(dataset$rank < dataset$lastpos))
  
  save(features, file = FEATURES_FILE)
  
}
```


Generate the model formula

```{r}
formula <- features %>%
  select(-response) %>%
  colnames() %>%
	paste(collapse = " + ") %>%
	paste("response ~", . )
```


Train-test split

```{r message=FALSE, warning=FALSE}
training_data <- features %>%
	sample_frac(0.5)

testing_data <- anti_join(features, training_data)
```


Fit the model

```{r message=FALSE, warning=FALSE}
if(file.exists(MODEL_FILE)) {
  
  load(MODEL_FILE)
  
} else {
  
  model <- cv.glmnet(
    as.matrix(select(training_data, -response)),
    pull(training_data, response),
    family = "binomial"
  )
  
  save(model, file = MODEL_FILE)
  
}
```


How many features did the model keep?

```{r}
plot(model)
coef(model)@i # index 1 (value 0) is the intercept

# https://stackoverflow.com/questions/29311323
```


Make predictions and assess accuracy

```{r}
predictions <- testing_data %>%
	mutate(soft_prediction = predict(model, newx = as.matrix(select(., -response)), type = "response")) %>%
	mutate(hard_prediction = soft_prediction >= 0.5) %>%
	mutate(is_correct      = hard_prediction == response)

paste("Accuracy: ", 100*round(mean(predictions$is_correct), 4), "%", sep = '')
```


```{r child="includes/prediction_distributions.Rmd"}
```


```{r child="includes/soft_prediction_distribution.Rmd"}
```


```{r child="includes/roc.Rmd"}
```

